[package]
name = "fst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"

[build-dependencies]
cc = "1.0"
pkg-config = "0.3.27"
bindgen = "0.69.1"
