[workspace]
members = [
  "libfst-sys",
  "fstapi"
]

[package]
name = "fst"
version = "0.1.0"
edition = "2021"
authors = ["shua <shua@isthisa.email>"]

[dependencies]
clap = "4.4.7"
env_logger = "0.10.0"
libfst-sys = { path = "./libfst-sys" }
log = "0.4.20"
